
import "./admins.css"
import NavBar from "./admin/ui/NavBar";
import SideBar from "./admin/ui/SideBar";
import { Toaster } from "react-hot-toast";
import "@uploadthing/react/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="h-[80px] md:pl-56 fixed inset-y-0 w-full z-50">
          <NavBar />
        </div>
        <div className="hidden md:flex h-full w-56 fixed flex-col inset-y-0 z-50">
          <SideBar />
        </div>
        <main className="md:pl-56 h-full pt-[80px]">
          <Toaster/>
          {children}
        </main>
      </body>
    </html>
  )
}
